### ISSUE TITLE
agent: broadcast to consoles before rebooting

### ISSUE THREAD

**Issue by lucab** [coreos/zincati#114]
This is a followup to https://github.com/coreos/fedora-coreos-tracker/issues/239.

Right now Zincati triggers a reboot in a silent way, which could surprise any logged users while they are in middle of some interactive maintenance.

For better user experience, it should somehow notify the users before triggering a reboot. Current proposal is to broadcast (i.e. `wall`) to all active consoles. This would match locksmith behavior.

**Comment by lucab** [comment]
Blocked until:
 * https://github.com/nix-rust/nix/issues/1111 is fixed
 * a new version of `nix` crate is published with the fix

**Comment by dustymabe** [comment]
+1 - I just had this idea today and there's already an open issue for it :heart:

**Comment by lucab** [comment]
Small update here, this is unfortunately blocked on a couple more levels of dependencies that need to be patched too, see https://github.com/rust-lang/libc/pull/1496#issuecomment-529109067.

**Comment by kelvinfan001** [comment]
Update: The implementation in #479 simply shells out to `loginctl` to get the list of logged in users. No longer requiring https://github.com/nix-rust/nix/issues/1111.
