### ISSUE TITLE
identity: expose deployment details as metrics

### ISSUE THREAD

**Issue by lucab** [coreos/zincati#120]
Zincati should gauge (and expose as a metrics) details from the booted OS version, as learned from rpm-ostree. This information is currently internally stored as part of `identity`, but never exposed.
This will help remote observers in detecting booted deployment changes, such as auto-updates or rollbacks.
Interesting details to expose:
 - [x] OS version (e.g. `zincati_identity_os_info{value="<XYZ>"} = 1`)
 - [ ] OS basearch (e.g. `zincati_identity_os_info{basearch="<XYZ>"} = 1`)
 - [ ] current stream (e.g. `zincati_identity_os_info{stream="<XYZ>"} = 1`)
 - [ ] platform (e.g. `zincati_identity_os_info{platform="<XYZ>"} = 1`)

Sidenote: best practise would be to have rpm-ostreed to expose this information on its own. However:
 * rpm-ostreed terminates itself when idle. I don't think we want to activate it every time just to get metrics while idling.
 * this information is relevant to auto-update monitoring, so it is likely a good idea to forward-expose it anyway.

/cc @jlebon wrt. metrics story for rpm-ostreed, I don't know if this was already covered somewhere.

**Comment by jlebon** [comment]
> /cc @jlebon wrt. metrics story for rpm-ostreed

We don't really have one. :)

That said, the current OS version is something that (obviously) doesn't change within a single boot, so I think collecting it from the same `rpm-ostree status --json` invocation Zincati already does should be enough, no? (As well as requerying it if the service is restarted of course).
