### ISSUE TITLE
rpm-ostree: failed to stage deployment

### ISSUE THREAD

**Issue by lucab** [coreos/zincati#124]
In a few random runs I've observed the following description-less rpm-ostree failure:

```
[INFO ] new release '30.20190801.0' selected, proceeding to stage it
[TRACE] request to stage release: Release { version: "30.20190801.0", checksum: "a9c8d66d3628d1b9b4c4690777e8b730d08329b4359410cb410a2003296af1ca", age_index: Some(2) }
[ERROR] failed to stage deployment: rpm-ostree deploy failed:


```

It looks like in some cases rpm-ostree can return a non-success exit code, but no output on stderr.

**Comment by jlebon** [comment]
Hmm, that sounds odd. To confirm, are we capturing stdout as well?

Given that this is likely an rpm-ostree issue too, if you hit this again, definitely try to check the journal and open an issue against https://github.com/coreos/rpm-ostree with details!

**Comment by lucab** [comment]
@jlebon no, we are only capturing (and printing) stderr.

I think I managed to manually reproduce this, at the least in the following case: if one tries to deploy a revision that was already deployed earlier, CLI exits with `77` and no output on stderr.

For example:
```
# rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
  ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 30.20190905.0 (2019-09-05T14:36:50Z)
                    Commit: b4beca154dab3696fd04f32ddab818102caa9247ec3192403adb9aaecc991bd9
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
                      Diff: 78 upgraded, 3 added

● ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 30.20190801.0 (2019-08-01T13:54:21Z)
                    Commit: a9c8d66d3628d1b9b4c4690777e8b730d08329b4359410cb410a2003296af1ca
              GPGSignature: (unsigned)

# rpm-ostree deploy --lock-finalization revision=b4beca154dab3696fd04f32ddab818102caa9247ec3192403adb9aaecc991bd9 1> /dev/null
# echo $?
77
```

On stdout, I see this instead:
```
Validating checksum 'b4beca154dab3696fd04f32ddab818102caa9247ec3192403adb9aaecc991bd9'
1 metadata, 0 content objects fetched; 569 B transferred in 3 seconds
1 metadata, 0 content objects fetched; 569 B transferred in 2 seconds
No change.
```

In which direction do we want to fix this?

**Comment by jlebon** [comment]
> CLI exits with `77` and no output on stderr.

Ahh right, that's the no-op case. It's kinda messy, though the same behaviour is available to `upgrade` with the `--upgrade-unchanged-exit-77` switch. `deploy` just has it turned on by default. Hmm, we could add a switch to not do that. Or maybe easier to just have Zincati handle rc 77?

**Comment by lucab** [comment]
Out-of-band discussion: let's update Zincati to also handle `77` as an "ok" exit status. @jlebon is also checking in background why `deploy` and `upgrade` behaviors are different, and if `deploy` should stick to `0` and grow a `--upgrade-unchanged-exit-77 switch`.

**Comment by jlebon** [comment]
https://github.com/coreos/rpm-ostree/pull/1906

**Comment by lucab** [comment]
I don't remember exactly how I encountered it the first time, but I was recently tweaking config manually and restarting to inspect service reaction and metrics.
One plausible scenario is that a deploy transaction managed to start before one of those restarts, and after that Zincati got stuck in this recurring-failure state.
