### ISSUE TITLE
container-linux-update-operator equivalent

### ISSUE THREAD

**Issue by george-angel** [coreos/zincati#214]
Is there something planned for zincati?

It would be nice to have the ability to drain nodes, and guarantee no collisions in restarts.

Thank you

**Comment by lucab** [comment]
General inquiries are better handled via https://discussion.fedoraproject.org/c/server/coreos.

Anyway, no there isn't any plan on our side to provide an update operator (to the best of my knowledge).

You can simply write your own operator with all the logic you require, and then point Zincati at it via the [lock-based finalization strategy](https://github.com/coreos/zincati/blob/master/docs/usage/updates-strategy.md#lock-based-strategy).

**Comment by cgwalters** [comment]
Note that [OKD4](https://github.com/openshift/okd/blob/master/README.md#getting-started) uses the [MCO](https://github.com/openshift/machine-config-operator/) with FCOS which does all of the draining, etc.
