### ISSUE TITLE
zincati: add metrics collection and reporting

### ISSUE THREAD

**Issue by lucab** [coreos/zincati#27]
For development/debugging purposes I'm currently maxing up logs to trace level. This is untenable on production environment, though we still want to observe internal state and metrics without spamming the journal.

Thus, we should sprinkle metrics collection points across the codebase, and periodically dump them to the filesystem in textual format, word-readable. At the other side of this, there will be a [Prometheus textfile collector](https://github.com/prometheus/node_exporter#textfile-collector) picking them up.

In detail, this means:
- [x] adding the `prometheus` crate (likely without the protobuf part)
- [x] adding an application-global registry
- [x] adding some initial metrics (all scoped under `zincati_`):
   - [x] gauge: state-machine last-refresh timestamp
   - [x] gauge: number of releases in cincinnati graph
- [x] adding a dedicated actor to serve metrics over a Unix-domain socket

Followup ticket for this would be adding more juicy info to observe state-machine transitions (ticks and timestamps) and success/error counters when calling external components (cincinnati, airlock, rpm-ostree). But let's sort the groundwork first.

**Comment by lucab** [comment]
@rfairley this requires first adding the `prometheus` crate, which is not currently in fedora. If you want to start having a look at that, I'll be holding this for a bit in order to make releasing and packaging the first version easier.

**Comment by rfairley** [comment]
@lucab thanks, on a first look, the `protobuf` crate will need adding to Fedora (which is straightforward), and a specific version of `hyper` is needed (may require modifications to `prometheus` upstream to use the newer `hyper` version existing in Fedora). Having a look further into the modifications needed.

**Comment by lucab** [comment]
Self note: suggestion from monitoring folks is to try to avoid the refresh interval and just react to scraping requests (e.g. via unix-socket or similar IPC). There are no exporters for this though.
