### ISSUE TITLE
agent: please report current update strategy and some basic info when started

### ISSUE THREAD

**Issue by jlebon** [coreos/zincati#305]
Right now, if I e.g. add a `/etc/zincati/config.d/90-updates.toml` with a config for the periodic strategy, there's no confirmation that this was picked up by Zincati when I `systemctl restart zincati`. I'd like something like:

```
...
[INFO ] initialization complete, auto-updates logic enabled
[INFO ] update strategy: periodic (next time window in 7h23m)
```

**Comment by jlebon** [comment]
Related: https://github.com/coreos/zincati/issues/94. If we had that and made sure to report the update strategy in the `STATUS` notification, I think maybe we wouldn't need this (though it wouldn't hurt either).

**Comment by lucab** [comment]
Agreed, I think this should be done on startup, regardless of what we do for #94. And we should forward this information to metrics too.

Regarding the periodic strategy, do you care about the next window in logs here specifically? I personally think that a more interesting info (from the point of monitoring and metrics too) is the total weekly schedule duration.

**Comment by jlebon** [comment]
> Regarding the periodic strategy, do you care about the next window in logs here specifically? I personally think that a more interesting info (from the point of monitoring and metrics too) is the total weekly schedule duration.

Could we log both? Hypothetical: if a config is overriding another config to change the day the window occurs, but not the duration, it wouldn't be possible to tell them apart.

**Comment by zonggen** [comment]
This also makes a lot of sense to me and could potentially very helpful when debugging and monitoring.

One thing I'm not entirely sure of regarding https://github.com/coreos/zincati/issues/94 is that when exposing the state of the agent, when should we log the current state? My assumption would be whenever the state changes and during startup.

**Comment by lucab** [comment]
I took the metrics part in https://github.com/coreos/zincati/pull/314, but the "log on startup" part is still to be done.

There is a piece of underlying logic missing, which is adding a function (and tests) in the `weekly` module to compute the remaining time to the next window. I guess the result would be a `Option<NonZeroU32>`. Plus a human time formatter for that result (possibly `chrono` already provides the basic logic).

Other than that, I think this new code could sit next to the other logging we do on startup, in its own `Settings::log_startup_info()`.
