### ISSUE TITLE
Update actix to 1.0.0

### ISSUE THREAD

**Issue by ignatenkobrain** [coreos/zincati#31]
Just yet another 1.x library :)

**Comment by lucab** [comment]
I think this hasn't reached 1.x yet, right? https://crates.io/crates/actix

Is there anything specific you observed in the transitive graph that concerns you?

PS: I plan to turn @dependabot on in here once we tag and package an initial release.

**Comment by ignatenkobrain** [comment]
That was my fault, I thought it is actix-web.
