### ISSUE TITLE
RFE: log an info level message when update is available, but present on disk

### ISSUE THREAD

**Issue by miabbott** [coreos/zincati#338]
During the workshop session at Fedora Nest, the ability to rollback to a previous deployment was demonstrated.  As part of the demo, we showed that `zincati` was running but did not try to download, change deployments, or reboot the host.

I believe it would be useful if an INFO level message was logged during this situation, telling users that there is an update available but it is already on disk.

**Comment by lucab** [comment]
I see the usability gain in surfacing this information. However Zincati performs such check every time it manages to fetch the graph from Cincinnati (i.e. on average every five minutes), so it doesn't look like a great idea spamming the logs each time.

I wonder whether we should:
 * print this information more succinctly only at startup (is it possible for new deployments to appear afterwards?)
 * put this information in metrics (only?)
 * lower the logging level below the default threshold (i.e. DEBUG or TRACE)

**Comment by miabbott** [comment]
> I see the usability gain in surfacing this information. However Zincati performs such check every time it manages to fetch the graph from Cincinnati (i.e. on average every five minutes), so it doesn't look like a great idea spamming the logs each time.
> 
> I wonder whether we should:
> 
>     * print this information more succinctly only at startup (is it possible for new deployments to appear afterwards?)

I think logging at startup would be great.  There's a chance a user may manually rebase/deploy a new ostree commit manually, but I think that is a corner case that doesn't need to be addressed.

**Comment by lucab** [comment]
Additional notes on this:
 * we don't know on start whether a locally-found deployment will (or will not) be a target for future updates, so the best we can do is printing how many and which has been found on startup (even if that includes older deployments). An `info` level message would work here.
 * the currently booted deployment is not interesting in this context, so care should be taken to **not** count that in.
 * the case where there aren't other deployments around is also not very interesting to a final user, so at most such case can be logged with a quick and dirty `debug` message.
 * as we are already querying rpm-ostree on each Cincinnati check, we should also put this gauged number into a metric, on top of printing and setting it on startup.

**Comment by miabbott** [comment]
@lucab @bh7cw thanks for the additional thoughts around how to handle this RFE.  I agree with the notes above and it looks like a well thought out approach on how to better inform an end user in the situation.
