### ISSUE TITLE
Error failed to register as driver: rpm-ostree deploy –register-driver failed

### ISSUE THREAD

**Issue by empikls** [coreos/zincati#588]
Hi,

I have problem when i start my service zincati in first time.
My instances are managed by terraform and when i check status of service i see error
```
[ERROR] failed to register as driver: rpm-ostree deploy --register-driver failed:
error: Transaction in progress: (null)
You can cancel the current transaction with rpm-ostree cancel
```
I can restart my service and error goes away, but i can’t do it manually on all my instances and terraform don’t allow restart services automatically .
Also when i first check `rpm-ostree status -b` i don’t see Zincati in front of BootedDeployment , but later after restart i see the following
```
AutomaticUpdatesDriver: Zincati
DriverState: active; periodically polling for updates (last checked Thu 2021-06-24 11:56:10 UTC)
```
Please help me with my case .

**Comment by lucab** [comment]
Thanks for the report. It looks like there was something else possibly interacting with rpm-ostree at the same time, which is however a bit unexpected. At the same, this should be a transient condition and the service unit should eventually restart and succeed without any manual intervention.
It would be interested to see `rpm-ostreed.service` and `zincati.service` journal logs to see how they are behaving.

/cc @kelvinfan001

**Comment by empikls** [comment]
@lucab @kelvinfan001 
Yes, sure. This is journal logs of rpm-ostreed.service :
Jun 25 06:06:55 rpm-ostree[6831]: Reading config file '/etc/rpm-ostreed.conf'
Jun 25 06:06:57  systemd[1]: Started rpm-ostree System Management Daemon.
Jun 25 06:06:57  rpm-ostree[6831]: In idle state; will auto-exit in 63 seconds
Jun 25 06:08:01  systemd[1]: rpm-ostreed.service: Deactivated successfully.
Jun 25 06:08:01  systemd[1]: rpm-ostreed.service: Consumed 2.561s CPU time.

and journal logs of zincati.service :
Jun 25 06:01:50  zincati[1079]: [INFO ] starting update agent (zincati 0.0.21)
Jun 25 06:01:52  zincati[1079]: [INFO ] Cincinnati service: https://updates.coreos.fedoraproject.org
Jun 25 06:01:52  zincati[1079]: [INFO ] agent running on node '6a2e898939b4489eaf78c370e9aa1ddd', in update group 'default'
Jun 25 06:01:52  zincati[1079]: [INFO ] registering as the update driver for rpm-ostree
Jun 25 06:01:53 zincati[1079]: [ERROR] failed to register as driver: rpm-ostree deploy --register-driver failed:
Jun 25 06:01:53  zincati[1079]:     error: Transaction in progress: (null)
Jun 25 06:01:53  zincati[1079]:      You can cancel the current transaction with `rpm-ostree cancel`
Jun 25 06:01:53  zincati[1079]:     
Jun 25 06:01:53  zincati[1079]: [INFO ] initialization complete, auto-updates logic enabled
Jun 25 06:01:53  zincati[1079]: [INFO ] update strategy: periodic, total schedule length 30 minutes; next window at 23:30 on Sat>
Jun 25 06:01:53  systemd[1]: Started Zincati Update Agent.
░░ Subject: A start job for unit zincati.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit zincati.service has finished successfully.
░░ 
░░ The job identifier is 435.
Jun 25 06:01:54 zincati[1079]: [INFO ] current release detected as not a dead-end

**Comment by kelvinfan001** [comment]
> At the same, this should be a transient condition and the service unit should eventually restart and succeed without any manual intervention.

To provide a little bit more clarification to this, `zincati.service` will not "restart" following a failed registration attempt. As of currently, Zincati will simply give up attempting to register as the updates driver for rpm-ostree after the first failed attempt at registration.

However, Zincati _will_ continue on with the rest of its initialization. Importantly, all of Zincati's functionality (around checking for and applying updates when possible) will still work as normal.

For more context, registering as the "updates driver" in rpm-ostree is mostly a UX improvement; see https://github.com/coreos/rpm-ostree/issues/2536. So far, the only difference that it makes is that, as you've noted, `rpm-ostree status` won't display Zincati as driving updates, and commands like `rpm-ostree upgrade` (not recommended on FCOS) will be allowed by default without having to `--bypass-driver`.

All that said, this is indeed a bug and I'll dig into it. Thanks!

**Comment by empikls** [comment]
@kelvinfan001 Thanks for your involvement! I will look forward to further investigation of this issue. I also want to add that I have applied the Periodic strategy update, and I will see how the ```zincati service``` will behaves. Currently, I have two types of instances - without applying the deployment strategy and with, both of them have a similar error - rpm-ostree status won't display Zincati as driving updates. So I will check in my side soon how it would work with deployment strategy ( this Sunday ) .

**Comment by kelvinfan001** [comment]
> It looks like there was something else possibly interacting with rpm-ostree at the same time,

Looking at the journal logs for `rpm-ostreed.service`, it doesn't look like it was handling any transactions, and the `(null)` transaction that is supposedly blocking Zincati's attempt to create a `deploy` transaction (to register as driver) looks mysterious to me. Digging into rpm-ostree's code a little bit, I couldn't find any reason for a transaction to be `null`, so I've filed that bug to rpm-ostree [here](https://github.com/coreos/rpm-ostree/issues/2968).

On Zincati's side, we could probably get Zincati to retry a couple of times to register as driver before giving up, but I don't feel like that is a proper solution to this problem, as it looks like the issue here lies more on the rpm-ostree side (since the logs show that rpm-ostree wasn't actually busy with any transaction). Another issue with retrying multiple times is that the amount of time for rpm-ostree to process each transaction varies greatly; I'm not sure if it is worth it to block Zincati initialization on driver registration. 
@lucab what do you think?

**Comment by empikls** [comment]
@kelvinfan001 for the experiment, I set up a new instance, here are the zincati.service logs from the very start :

Jul 07 07:09:24 zincati[1077]: [INFO ] starting update agent (zincati 0.0.21)
Jul 07 07:09:26 zincati[1077]: [INFO ] Cincinnati service: https://updates.coreos.fedoraproject.org
Jul 07 07:09:26 zincati[1077]: [INFO ] agent running on node '0277c06444bf43bc857f53a05dc73498', in update group 'default'
Jul 07 07:09:26 zincati[1077]: [INFO ] registering as the update driver for rpm-ostree
Jul 07 07:09:27 zincati[1077]: [ERROR] failed to register as driver: rpm-ostree deploy --register-driver failed:
Jul 07 07:09:27 zincati[1077]:     error: Transaction in progress: (null)
Jul 07 07:09:27 zincati[1077]:      You can cancel the current transaction with `rpm-ostree cancel`
Jul 07 07:09:27 zincati[1077]:     
Jul 07 07:09:28 zincati[1077]: [INFO ] initialization complete, auto-updates logic enabled
Jul 07 07:09:28 zincati[1077]: [INFO ] update strategy: periodic, total schedule length 30 minutes; next window at 23:30 on Sat (Europe/Kiev), subject to >
Jul 07 07:09:28 systemd[1]: Started Zincati Update Agent.
░░ Subject: A start job for unit zincati.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit zincati.service has finished successfully.
░░ 
░░ The job identifier is 437.
Jul 07 07:09:28 zincati[1077]: [INFO ] current release detected as not a dead-end
Jul 07 07:09:29 zincati[1077]: [INFO ] target release '34.20210626.1.0' selected, proceeding to stage it
Jul 07 07:09:29 zincati[1077]: [ERROR] failed to stage deployment: rpm-ostree deploy failed:
Jul 07 07:09:29 zincati[1077]:     error: Transaction in progress: kargs --append 'mitigations=auto tsx=auto'
Jul 07 07:09:29 zincati[1077]:      You can cancel the current transaction with `rpm-ostree cancel`
Jul 07 07:09:29 zincati[1077]
Jul 07 07:14:53 zincati[1077]: [INFO ] target release '34.20210626.1.0' selected, proceeding to stage it

And when I check rpm-ostree status -b :
State: idle
BootedDeployment:
● ostree://fedora:fedora/x86_64/coreos/next
                   Version: 34.20210611.1.0 (2021-06-14T14:54:15Z)
                    Commit: 72ca343ceadd3734af6.....
              GPGSignature: Valid signature by 8C5BA6990B....

**Comment by lucab** [comment]
@empikls it looks like there are some other tasks running on this machine at boot, like settings `kargs` through `enable-smt-subsequentboot.service`. Are those part of the node Butane/Ignition configuration? If so, can you please share your whole node configuration (after redacting secrets) so that we can try to reproduce this?

In general if there are some other services interacting with rpm-ostree daemon (and possibly rebooting the machine), the units should have proper Before/After dependencies to make sure they run in a deterministic order.

**Comment by empikls** [comment]
@lucab yes, ```enable-smt-subsequentboot.service``` is a part of the node Ignition configuration . 
The whole node configuration look like this : 

# Ignition config
data "ignition_config" "user_data" {
  users       = [for user in data.ignition_user.users : user.rendered]
  groups      = [for group in data.ignition_group.groups : group.rendered]
  filesystems = [for volume in data.ignition_filesystem.volumes : volume.rendered]
  directories = [for dir in data.ignition_directory.dirs : dir.rendered]
  systemd = concat(
    [
      data.ignition_systemd_unit.metadata.rendered,
      data.ignition_systemd_unit.rpc_statd.rendered,
      data.ignition_systemd_unit.zincati.rendered,
      data.ignition_systemd_unit.docker_dropins.rendered,
      data.ignition_systemd_unit.enable_smt_firstboot.rendered,
      data.ignition_systemd_unit.enable_smt_subsequentboot.rendered,
    ],
    [for volume in data.ignition_systemd_unit.volumes : volume.rendered],
  )
  files = concat(
    [
      data.ignition_file.zincati_strategy.rendered,
      data.ignition_file.sysctl_net.rendered,
      data.ignition_file.modprobe_net.rendered,
      data.ignition_file.sysconfig_docker.rendered,
      data.ignition_file.selinux.rendered,
      data.ignition_file.ebs_udev.rendered,
      data.ignition_file.ebs_nvme.rendered,
      
    ],
    [for tmpfile in data.ignition_file.tmpfiles : tmpfile.rendered]
  )
}

Ignition for services:

data "ignition_systemd_unit" "metadata" {
  name    = "afterburn.service"
  enabled = true
}

data "ignition_systemd_unit" "rpc_statd" {
  name    = "rpc-statd.service"
  enabled = true
}

data "ignition_systemd_unit" "zincati" {
  name    = "zincati.service"
  enabled = false
}


data "ignition_systemd_unit" "docker_dropins" {
  name = "docker.service"
  dropin {
    name    = "increase-ulimit.conf"
    content = <<EOF
[Unit]
After=${join(" ", [for volume in data.ignition_systemd_unit.volumes : volume.name])}
Requires=${join(" ", [for volume in data.ignition_systemd_unit.volumes : volume.name])}

[Service]
ExecStart=
ExecStart=/usr/bin/dockerd \
          --host=fd:// \
          $OPTIONS
LimitMEMLOCK=infinity
EOF
  }
}

data "ignition_systemd_unit" "enable_smt_firstboot" {
  name    = "enable-smt-firstboot.service"
  enabled = true
  content = <<EOF
[Unit]
DefaultDependencies=no
Before=sysinit.target shutdown.target
Conflicts=shutdown.target
ConditionFirstBoot=true

[Service]
Type=oneshot
ExecStart=/bin/bash -c 'active="$(cat /sys/devices/system/cpu/smt/active)" && if [[ "$active" != 1 ]] && grep -q "vendor_id.*GenuineIntel" /proc/cpuinfo; then echo "Enabling SMT." && echo on > /sys/devices/system/cpu/smt/control; fi'

[Install]
WantedBy=sysinit.target
EOF
}

data "ignition_systemd_unit" "enable_smt_subsequentboot" {
  name    = "enable-smt-subsequentboot.service"
  enabled = true
  content = <<EOF
[Unit]
Description=Enable SMT on subsequent boots by changing kernel arguments
ConditionFirstBoot=true

[Service]
Type=oneshot
ExecStart=/usr/bin/rpm-ostree kargs --append "mitigations=auto tsx=auto"

[Install]
WantedBy=multi-user.target
EOF
}

**Comment by kelvinfan001** [comment]
@empikls I have been able to reproduce this problem. Looking at the Ignition configuration you provided, I believe the conflict is caused by `enable-smt-subsequentboot.service`. In the meantime, a work around would be to [order this unit around `zincati.service`](https://github.com/coreos/zincati/blob/v0.0.22/dist/systemd/system/zincati.service), for example, you can add a `Before=boot-complete.target` dependency to `enable-smt-subsequentboot.service`.

**Comment by empikls** [comment]
@kelvinfan001 Great! I've set up instances with ```Before=boot-complete.target``` dependency in ```enable-smt-subsequentboot.service``` and error was gone for ```zincati.service``` . Also rpm-ostree status display Zincati as driving updates . I checked three times and got a positive result . 
Thanks a lot for investigation and support!
