### ISSUE TITLE
identity: check whether current stream is meant to auto-update

### ISSUE THREAD

**Issue by lucab** [coreos/zincati#60]
At the moment Zincati tries to always auto-update the OS, regardless of its stream.

This is fine on production streams. There are however few cases where this doesn't make much sense, for example mechanical and development streams.

It would be good to expose a configurable list of streams for which auto-updates are enabled. Default configuration would allow production streams only.

Raw plan:
 * Add a `stream_whitelist` configuration entry (`HashSet<String>`)
 * Add logic for override-merging stream entries from multiple configuration fragments
 * Add a default TOML configuration fragment with `[ "stable", "next", "testing" ]`
 * Fast-forward update-agent state-machine to `EndState` if the current stream is not in the whitelist

Blockers:
 - [ ] https://github.com/coreos/zincati/issues/55

**Comment by jlebon** [comment]
See https://github.com/coreos/fedora-coreos-tracker/issues/163#issuecomment-508847356 for a different approach. To directly address this specific issue's title:

Zincati would be configured appropriately for each individual stream, so it wouldn't have to care about specific stream names.

**Comment by lucab** [comment]
Closing in favor of https://github.com/coreos/zincati/issues/62.
