### ISSUE TITLE
identity: check whether current image is meant to auto-update

### ISSUE THREAD

**Issue by lucab** [coreos/zincati#61]
At the moment Zincati tries to always auto-update the OS, regardless of its stream.

This is fine on production images. There are however few cases where this doesn't make much sense, for example when somebody is performing a local build from a configuration/lockfile belonging to a production stream.

In that case, Zincati will reach out to the updates server and get an update-graph for the relevant stream, but it won’t find its own self-matching node (version+checksum tuple) in there, wasting both client-side and server-side resources. As backend operators, the latter concerns us directly.

It would be good to have a mechanism to detect local-development built, in order to avoid trying to update them.

**Comment by jlebon** [comment]
@bgilbert will open an issue to start a higher-level discussion about how to handle "devel" vs "prod" differences.

**Comment by bgilbert** [comment]
https://github.com/coreos/fedora-coreos-tracker/issues/212

**Comment by lucab** [comment]
@jlebon @bgilbert my understanding is that it has been superseded in the meanwhile by https://github.com/coreos/zincati/issues/62, right? If so, I guess this can be closed.

**Comment by jlebon** [comment]
Yeah, I think we can close this.
