### ISSUE TITLE
Disable Zincati when booting a live image

### ISSUE THREAD

**Issue by bgilbert** [coreos/zincati#63]
It won't work on PXE or ISO anyway.

I think the most direct approach would be to make `zincati.service` `ConditionKernelCommandLine=!` the kargs for PXE and ISO booting.  Do we want to do that upstream, or should the distro add a drop-in?

**Comment by lucab** [comment]
Zincati is already very much specific to Fedora-CoreOS. It also already depends specifically on Ignition platform ID: https://github.com/coreos/zincati/blob/d4f5d743bcb975583a35a6a64dd1f6fb0827264f/src/identity/platform.rs#L14

Both options would be fine, but I guess that adding the condition here will make it will simpler to read and reason about for our users.

**Comment by bgilbert** [comment]
Unlike on Container Linux, the Ignition platform ID will not encode PXE and ISO boot.  There will be separate kargs for that.

**Comment by lucab** [comment]
Ah, true. Scratch the bits on Ignition platform then. Let's still keep those conditions here, once we settle on the new kargs.

**Comment by lucab** [comment]
Closed by https://github.com/coreos/zincati/pull/126.
