### ISSUE TITLE
Dynamic configuration

### ISSUE THREAD

**Issue by nivekuil** [coreos/zincati#754]
# Feature Request #

I am writing a consul fleetlock server and want to configure zincati's update strategy dynamically depending on whether the server is running on the host. Currently it seems like the only time zincati reads the config is when it restarts but this is a little hard to pull off from a container. It would be nice if zincati watched the config directories or if I could send a reload command somehow.

**Comment by cgwalters** [comment]
I think from a privileged container you can `systemctl restart zincati`.

**Comment by lucab** [comment]
Thanks for the report. Yes, configuration reloading (i.e. graceful agent reset) is a missing feature which could be added to Zincati. The idea is that this should be exposed through the DBus interface. This request is already tracked in https://github.com/coreos/zincati/issues/673, thus I'm closing this ticket.

However for your specific usecase I think that @cgwalters's suggestion is a good one: `systemctl restart zincati` goes through DBus as well, so you'll need a privileged container either for interacting with systemd or for interacting with Zincati. At that point, a full service restart is likely a better option.
