### ISSUE TITLE
Get Graph from SubPath

### ISSUE THREAD

**Issue by modzilla99** [coreos/zincati#819]
# Feature Request #
We'd like to request that zincati will respect subpaths in URLs. Right now it will only accept `sub.domain.tld` and completly disregard any subpath like this `sub.domain.tld/subpath/`. 

## Desired Feature ##
Let Zincati use a graph from a subpath. Setting `domain.tld/subpath` should make Zincati pull from `domain.tld/subpath/v1/graph`.

## Example Usage ##
We need that to fix the CoreOS version with a specific update graph for every kubernetes Version. (`domain.tld/v1.24` for example)

**Comment by lucab** [comment]
Thanks for the report.
Have you already tried setting it through configuration files?
It should already work if you set your custom base URL through a snippet like this:
```
# cat /etc/zincati/config.d/10-custom-base.toml
[cincinnati]
base_url="https://foo.example.com/bar/"
```

**Comment by modzilla99** [comment]
Yes, my bad! Just found it as well! Thank you! :)
