### ISSUE TITLE
cincinnati: configure rollout wariness

### ISSUE THREAD

**Issue by lucab** [coreos/zincati#82]
Cincinnati backend will add support for throttling new release rollouts over a period of time.

By default, the whole process is performed by the backend without any client explicit client involvement:
 1. at any point in time, a rolling-out release is assigned a throttling value `X`, sliding from 0.0 (start) to 1.0 (full rollout)
 1. each client request is arbitrarily assigned a rollout wariness score `Y`, between 0.00001 (bold) and 1.0 (careful)
 1. if `X < Y`, the update-graph (for this request) will be pruned of all incoming edges to the throttled release

However, it would be nice for the server to allow clients to pick their own wariness score.
On the client-side, this means exposing a `rollout_wariness` in configuration, and forwarding it to Cincinnati.

**Comment by lucab** [comment]
This requires some throttling coordination with the server, which is ongoing at https://github.com/openshift/cincinnati/pull/130#issuecomment-507718938.

**Comment by lucab** [comment]
For reference, current OpenShift draft has a "sucess rate" for releases and a "risk appetite" for clients, in the 0.0 to 1.0 range.
The pruning-decision logic is the same as the one described above.

**Comment by lucab** [comment]
@arithx I have a PR up for this at https://github.com/coreos/zincati/pull/97. However I'd like some UX double-check, bikeshedding encouraged.

The proposed usage is a `identity.rollout_wariness = <float>` configuration entry, with allowed values in the `[0.0, 1.0]` range.

**Comment by arithx** [comment]
I think that at a glance `identity` didn't seem like the most obvious grouping until I looked into the context of what else was contained in it.

As for `rollout_wariness` I think that does a good job at conveying the intent. If you're searching for other ideas in general maybe something like `update_tolerance` or `update_confidence`?

**Comment by lucab** [comment]
> I think that at a glance `identity` didn't seem like the most obvious grouping until I looked into the context of what else was contained in it.

A few alternative options we could check:
 * rename the `identity` section. It currently contains `node_uuid` and `group`, which are sent to both Cincinnati and Airlock. I don't have better ideas for naming, though.
 * move to the `cincinnati` section. Though I was planning for this section to only container HTTP-releated parameters (address, auth, tls CA, etc.)
 * move to the `updates` section. At the moment it contains only "strategy" and enablement bool. I am not sure it is a good fit here, as we are talking about a parameter that is going to be sent to a remote server, while update knobs so far have only local effects.

> As for rollout_wariness I think that does a good job at conveying the intent. If you're searching for other ideas in general maybe something like update_tolerance or update_confidence?

Then I'd stick with the current name. The scale goes from 0.0 (bold, min wariness) to 1.0 (cautious, max wariness). Your other suggestions seem to need a scale going in the opposite direction.
