### ISSUE TITLE
tests: investigate failpoints

### ISSUE THREAD

**Issue by lucab** [coreos/zincati#84]
I'd like to start looking into [fault-injection testing](https://en.wikipedia.org/wiki/Fault_injection) this agent, via the `fail` library: https://docs.rs/fail/0.3.0/fail/

This likely requires first packaging the source crate in Fedora.

/cc @rfairley

**Comment by rfairley** [comment]
:+1: - this crate looks to have all its dependencies already packaged in Fedora. Will open a package review request shortly.

**Comment by rfairley** [comment]
Package review request: https://bugzilla.redhat.com/show_bug.cgi?id=1732920

**Comment by rfairley** [comment]
SCM repo requested: https://pagure.io/releng/fedora-scm-requests/issue/13866

**Comment by rfairley** [comment]
Build for `rust-fail` now complete: https://koji.fedoraproject.org/koji/buildinfo?buildID=1334946, this crate should now be :+1: to use

**Comment by lucab** [comment]
Initial one landed in https://github.com/coreos/zincati/pull/92, closing.
