### ISSUE TITLE
cincinnati: expose dead-end release information

### ISSUE THREAD

**Issue by lucab** [coreos/zincati#90]
There is a vague idea for the Cincinnati server to encode the "version is a dead-end" information in the graph served to clients.

If/when that happens, Zincati could take a proactive approach and notify that somehow to a monitoring system or to a human (e.g. via metrics/env-file/motd/etc).

**Comment by lucab** [comment]
@bgilbert behavioral doubt: what should the client do when it detects that it is running on a dead-end release? Should it kept polling for updates (in case the server changes its graph) or can it assume it will never get out of it and park itself?

**Comment by bgilbert** [comment]
Doesn't Cincinnati inherently encode that a version is a dead-end, by not having any out-edges?

IMO it should keep polling.  Otherwise, if we ever published a graph with incorrect dead-end nodes (or even just changed our minds), there'd be no way to fix it without user intervention.
