### ISSUE TITLE
agent: should warn when run by other users

### ISSUE THREAD

**Issue by arithx** [coreos/zincati#95]
When `zincati agent` is ran by other users (e.x. `core`) instead of the `zincati` user it will fail with a `Permission Denied` error. We should detect the user and warn if it's not correct.

This is what the error looks like when being ran from the `core` user:
```
$ zincati -v agent
[INFO ] starting update agent (zincati 0.0.3)
[INFO ] agent running on node 'c5673158671d4c5996b8c1d0da025ca6' in group 'default'
Error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

failed to bind metrics service
```

NOTE: I stumbled across this while just playing around with the OS and saw the binary.

**Comment by lucab** [comment]
I agree with this.

The agent should be checking that it is running as the `zincati` user.
The proper place where to put this check would be within [`run_agent`](https://github.com/coreos/zincati/blob/0.0.4/src/main.rs#L53).
Helper library method to use is https://docs.rs/users/0.9.1/users/fn.get_current_username.html.
